### ISSUE TITLE
Cannot use -nw option because of terminfo

### ISSUE THREAD

**Issue by SebastianMpl** [ivan-hc/Emacs-appimage#1]
Hi,

Thank you for the Emacs Appimage.
Only issue that I found is that when I start Emacs with -nw i get:
emacs: Cannot open terminfo database file

And only GUI mode works.

Is it possible to modify the build so -nw could work?

Thank you

**Comment by ivan-hc** [comment]
Hi, I started a new workflow run (wait until the end of [this](https://github.com/ivan-hc/Emacs-appimage/actions/runs/8411982292) for the new release) including the following changes https://github.com/ivan-hc/Emacs-appimage/commit/6f8b7777cb53cc31adff8716fbdfa44b0442332f :
- if started from terminal using an option, you will use `emacsclient`;
- included `libselinux` for a more wide compatibility with host's libraries (experimental, see https://github.com/ivan-hc/ArchImage/issues/20);
- included all dependences (about 10 MB bigger).

In my tests I've launched the following command:
```
./*.AppImage -nw
```
and I got this message:
```
emacsclient: can't find socket; have you started the server?
emacsclient: To start the server in Emacs, type "M-x server-start".
emacsclient: No socket or alternate editor.  Please use:

	--socket-name
	--server-file      (or environment variable EMACS_SERVER_FILE)
	--alternate-editor (or environment variable ALTERNATE_EDITOR)
```
I'm not sure if I miss something to include in the bundle, but I'm not an Emacs expert... maybe this works for you. Check it out.

**Comment by SebastianMpl** [comment]
I get the same error as you. But its different than that with terminfo. Something is happening...

**Comment by ivan-hc** [comment]
@SebastianMpl well, let me know if its something god or bad

**Comment by SebastianMpl** [comment]
No, its fine, GUI works as prevoius but regarding nw now we have the issue as above. I'm also not an emacs expert but if I find some solution I'll let you know.

**Comment by ivan-hc** [comment]
Note that if the message above is related to some apps to use from Emacs itself... just know that this is not a normal Appimage. I call it "Archimge", this is an Arch Linux container (JuNest) into an AppImage. There is no way (for now) to use external apps and programs other than the ones bundled into the AppImage.

If you need to compare this and perform tests... there is someone else that have built Emacs as Appimages:

https://github.com/blahgeek/emacs-appimage

it seems that these are built from source, so them should be widelly compatible fith the host system.

**Comment by ivan-hc** [comment]
Hi, sorry for the long wait, I just started another workflow for a new bouild https://github.com/ivan-hc/Emacs-appimage/actions/runs/10426241902

Not much changes, abart its internal bubblewrap that now mounts /var

I think that the issue is the same I have with my AppImage of Gnome Boxes. Since "sockets" are mounted in /var, you need that the system service is started.

That said, you need to install the dedicated service system-wide. Normally they are mounted in /var, and the new AppImage will see it.

If this solves the issue let me know.

**Comment by ivan-hc** [comment]
I close this issue for inactivity
